# generated by datamodel-codegen:
#   filename:  book-webapp-fastapi_API-specification.yaml
#   timestamp: 2022-08-08T02:43:29+00:00

from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, Field


class Book(BaseModel):
    id: str = Field(..., description='Unique identifier for the given book.')
    title: str
    author: Optional[str] = None
    category: str
    country: Optional[str] = None
    publishDate: Optional[date] = Field(
        None,
        description="Set to true if the book's email has been verified.",
        example='2022-08-10',
    )
    createdDatetime: Optional[datetime] = Field(
        None, description='The date that the book was created.'
    )
    updatedDatetime: Optional[datetime] = Field(
        None, description='The date that the book was created.'
    )
