POST http://127.0.0.1:8080/books
Authorization: "Bearer abcd"
Content-Type: application/json

{
  "id": "0142",
  "title": "Software Design 2022.08",
  "author": "someone",
  "company": "技術評論社",
  "category": "technology",
  "country": "Japan",
  "publishDate": "2019-08-24"
}

###
PUT http://127.0.0.1:8080/books/12
Authorization: "Bearer abcd"
Content-Type: application/json

{
  "id": "0142",
  "title": "Software Design 2022.08",
  "author": "someone",
  "company": "技術評論社",
  "category": "technology",
  "country": "Japan",
  "publishDate": "2019-08-24"
}
###
GET http://127.0.0.1:8080/books/1230
Authorization: "Bearer abcd"

####
DELETE http://127.0.0.1:8080/books/123
Authorization: "Bearer abcd"
