POST http://127.0.0.1:8080/books
Authorization: "Bearer abcd"
Content-Type: application/json

{
  "id": "0142",
  "title": "Software Design 2022.08",
  "author": "someone",
  "company": "技術評論社",
  "category": "technology",
  "country": "Japan",
  "publishDate": "2019-08-24"
}

###
PUT http://127.0.0.1:8080/books/12
Authorization: "Bearer abcd"
Content-Type: application/json

{
  "id": "0142",
  "title": "Software Design 2022.08",
  "author": "someone",
  "company": "技術評論社",
  "category": "technology",
  "country": "Japan",
  "publishDate": "2019-08-24"
}
###
GET http://127.0.0.1:8080/books/1230
Authorization: "Bearer abcd"

####
DELETE http://127.0.0.1:8080/books/123
Authorization: "Bearer abcd"
#####pet example###############################################
# $ curl -s -D /dev/stderr -X GET -H "Accept:application/json" http://localhost:4010/pet/0001?hoge=dow | json_pp
# -s : not show progress
# -D : show response header
# -H : header
# -u : basic authorization
# >>> Add authorization header
# >>>>> Authorization: Basic username:password
GET http://127.0.0.1:8080/pet/0001?hoge=dow
Accept: application/json
# Authorization: "Accept:application/json"
####
GET http://127.0.0.1:8080/user/login?username=corrupti&password=iste
####
GET http://127.0.0.1:8080/store/order/8
####
GET http://127.0.0.1:8080/pet/436357421
Content-Type: application/json
api_key: "aaa"
